# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRbBmoelbjy-GnXllZpneUOskQxJZ_-J
"""

import pandas as pd

df_airlines = pd.read_csv('/content/nyc_airlines.csv')
df_airports = pd.read_csv('/content/nyc_airports.csv')
df_airflight_fixed = pd.read_csv('/content/nyc_flights_fixed.csv')
df_planes = pd.read_csv('/content/nyc_planes.csv')
df_weather = pd.read_csv('/content/nyc_weather.csv')

df_airlines['carrier'].unique()

df_airlines.head()

df_airflight_fixed.head()

df_filter = df_airflight_fixed[df_airflight_fixed['origin']=='EWR']

len(df_filter['dest'].unique())

df_filter['dest'].unique()

"""#Rank Total Flights"""

df_join = pd.merge(df_filter,df_airlines,on='carrier', how='left')
df_join.head()

df_airlines_rank = df_join.groupby(['carrier', 'name']).agg(total_flight=('flight', 'count')).reset_index()
df_airlines_rank.sort_values(by='total_flight', ascending=False).reset_index().drop('index', axis=1)

"""#Total Delay"""

df_delays = df_filter.groupby(['month']).agg(total_delay=('dep_delay', 'sum')).reset_index()
df_delays['cumulative_delays'] = df_delays['total_delay'].cumsum()

df_delays

import matplotlib.pyplot as plt

plt.bar(df_delays['month'], df_delays['total_delay'], color='g')
plt.plot(df_delays['month'], df_delays['cumulative_delays'], color='b')
plt.show()

"""# No of Unique flights to EWR"""

df_airflight_fixed['year'].unique()



df_agg = df_airflight_fixed.groupby(['month'])['dest'].nunique()

df_agg

df_agg = df_filter.groupby(['month'])['dest'].nunique()
df_agg

"""#Monthly Flights"""

df_month_count = df_filter.groupby(['month']).agg(count_dest=('dest', 'count'))
df_month_count

df_month_count = df_month_count.reset_index().rename(columns={'count_dest': 'count'})
df_month_count

import matplotlib.pyplot as plt

plt.bar(df_month_count['month'], df_month_count['count'])
plt.show()